questions=[{"question":"When was Kerala state formed?","options":["A.1947","B.1950","C.1956","D.1960"],"answer":"C"},
{"question":"Which is the longest river in Kerala?","options":["A.Bharathapuzha","B.Periyar","C.Pamba","D.Chaliyar"],"answer":"B"},
{"question":"Which district in Kerala is known as the 'Land of Letters'?","options":["A.Kottayam","B.Kozhikode","C.Thrissur","D.Kollam"],"answer":"A"},
{"question":"Who was the first Chief Minister of Kerala?","options":["A.Pattom Thanu Pillai","B.C. Achutha Menon","C.E.M.S. Namboodiripad","D.K. Karunakaran"],"answer":"C"},
{"question":"Which is the largest district in Kerala by area?","options":["A.Palakkad","B.Malappuram","C.Idukki","D.Ernakulam"],"answer":"C"},
{"question":"What is the official state bird of Kerala?","options":["A.Peacock","B.Great Hornbill","C.Kingfisher","D.Woodpecker"],"answer":"B"},
{"question":"In which year was the first Malayalam movie 'Vigathakumaran' released?","options":["A.1928","B.1930","C.1933","D.1940"],"answer":"A"},
{"question":"Which Kerala city is known as the 'Queen of the Arabian Sea'?","options":["A.Kollam","B.Kochi","C.Thiruvananthapuram","D.Alappuzha"],"answer":"B"},
{"question":"Who is known as the 'Father of Malayalam Literature'?","options":["A.Vallathol Narayana Menon","B.Kumaran Asan","C.Thunchaththu Ezhuthachan","D.Cherusseri Namboothiri"],"answer":"C"},
{"question":"Which lake is the largest in Kerala?","options":["A.Ashtamudi Lake","B.Pookode Lake","C.Vembanad Lake","D.Sasthamkotta Lake"],"answer":"C"},
{"question":"How many districts were there in Kerala at the time of its formation in 1956?","options":["A.5","B.7","C.9","D.14"],"answer":"A"},
{"question":"In August 2025, Kerala became the first state in India to achieve which milestone?","options":["A.100% Organic Farming","B.100% Digital Literacy","C.100% Electric Public Transport","D.First Zero-Waste State"],"answer":"B"},
{"question":"Which major seaport in Kerala is being developed as India's first deep-water transshipment hub?","options":["A.Kochi Port","B.Beypore Port","C.Vizhinjam Port","D.Azheekal Port"],"answer":"C"},
{"question":"What is the name of the state-run project providing high-speed internet to over 30,000 government offices and free internet to low-income families?","options":["A.K-SMART","B.K-FON","C.Digi Keralam","D.Akshaya 2.0"],"answer":"B"},
{"question":"In March 2026, the Prime Minister laid the foundation stone for a major Polypropylene Unit at which Kerala facility?","options":["A.FACT Kochi","B.BPCL Kochi Refinery","C.HMT Kalamassery","D.KINFRA Park"],"answer":"B"},
{"question":"Which Kerala city is the home of India's first 'Water Metro' service?","options":["A.Kozhikode","B.Alappuzha","C.Kochi","D.Thiruvananthapuram"],"answer":"C"},
{"question":"Which local self-governing platform was launched to digitalize all services of local bodies in Kerala?","options":["A.Sevana","B.K-SMART","C.E-Gram","D.Panchayat Online"],"answer":"B"},
{"question":"The proposed 'SilverLine' project in Kerala is related to which sector?","options":["A.High-speed Internet","B.Semi-high-speed Rail","C.Coastal Highway","D.Silver Mining"],"answer":"B"},
{"question":"Which district in Kerala is the site for the proposed Sabarimala Greenfield International Airport?","options":["A.Idukki","B.Pathanamthitta","C.Kottayam","D.Kollam"],"answer":"C"},
{"question":"Which Kerala city became the first in India to be designated as a 'UNESCO City of Literature'?","options":["A.Thrissur","B.Kottayam","C.Kozhikode","D.Thiruvananthapuram"],"answer":"C"},
{"question":"Kerala aims to become a completely 'Carbon Neutral' state by which target year?","options":["A.2030","B.2040","C.2050","D.2070"],"answer":"C"}
]